name: Deploy Bicep files $(Build.BuildId)

trigger:
 batch: true
 branches:
  include:
    - main
   
pool:
  vmImage: 'ubuntu-latest'

variables:
- name : templateFilePath
  value: 'Demo/main.bicep'
- name : parametersFolderPath
  value: 'Demo/azuredeploy.parameters.json'
- name : GrupoRecursos
  value: 'Demo'
- name:  location
  value: 'southcentralus'

 

stages:
- stage: preDeploy
  jobs:
  - job: scanWhatif
    displayName: scan and run whatif
    pool:
      vmImage: windows-2022

    steps:
    
    - task: RunARMTTKTests@1
      displayName: Scan Bicep files
      inputs:
        templatelocation: '$(System.DefaultWorkingDirectory)\Demo'
        resultLocation: '$(System.DefaultWorkingDirectory)\results'
        allTemplatesMain: false
        cliOutputResults: true
        ignoreExitCode: true

    - task: PublishTestResults@2
      displayName: Publish Results
      inputs:
        testResultsFormat: 'NUnit'
        testResultsFiles: '$(System.DefaultWorkingDirectory)\results\*-armttk.xml'
      condition: always()

    - task: AzureCLI@2
      displayName: Preview Bicep Changes
      inputs:
        azureSubscription: 'Test'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az --version
          az group create --name $(GrupoRecursos) --location $(location)
          az deployment group what-if --resource-group $(GrupoRecursos) \
            --template-file $(templateFilePath) \
            --parameters @azuredeploy.parameters.json

- stage: deployBicep
  jobs:

  - job: waitForValidation
    displayName: Wait for external validation
    pool: server
    timeoutInMinutes: 4320 # job times out in 3 days
    steps:
    - task: ManualValidation@0
      timeoutInMinutes: 1440 # task times out in 1 day
      inputs:
        notifyUsers: 'sada2022as@outlook.com'
        instructions: 'Please validate the build $(Build.BuildId) configuration and resume'
        onTimeout: 'resume'

  - job: deployAzure
    displayName: deploy bicep to Azure
    pool:
      vmImage: 'ubuntu-latest'
    dependsOn: [waitForValidation]

    steps:
    - task: AzureCLI@2
      displayName: Deploy Bicep To Azure
      inputs:
        azureSubscription: 'Test'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment group create --resource-group $(GrupoRecursos) \
            --template-file $(templateFilePath) \
            --parameters @azuredeploy.parameters.json
